before_script:
  - psql -c 'create database cycling-service-test;' -U cyclingservices

language: ruby
rvm:
  - "2.1.2"
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec